org.gradle.jvmargs=-Xmx2048M
modName = StructureLib

# This is a case-sensitive string to identify your mod. Convention is to use lower case.
archive_base_name = structurelib

maven_group =org.gt-reimagined
mod_id=structurelib

minecraft_version = 1.20.1
forge_version = 47.4.0
mappings_version=2023.09.03
fabric_api_version=0.92.5
fabric_loader_version=0.16.7
mod_version=4.0.0
nightconfig_version=3.6.5
port_lib_version=2.3.8
resourcefullib_version=2.1.29
carbon_config_fabric_version=ympPiBMO
carbon_config_forge_version=4XClxEgC
